# Generated by Django 3.1 on 2020-11-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutriFit', '0002_auto_20201118_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutriFit.utilizador'),
        ),
    ]
