# Generated by Django 3.1 on 2020-11-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriFit', '0004_auto_20201121_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ci',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='objetivo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
