# Generated by Django 3.1 on 2020-11-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriFit', '0006_auto_20201121_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
